add compare phone number to duplicate finder
noam-honig/food-basket-delivery pull request #608
Opened 2020-09-28 12:45 UTC by morfi11

בינתיים לא הסתבכתי עם ההופנים. לא נראה שצריך לפחות בשלב ראשון. השוואת מספר טלפון עושה את העבודה. 
אולי פשוט נשתמש במספר הטלפון לבדוק בזמן הרישום? התורם יקבל פופאפ - "מספר טלפון זה נמצא כבר במערכת לתרומה של <>, האם אתם תורמים ציוד נוסף כעת?"

2020-09-29 05:38 UTC, noam-honig requested changes
זה פחות הכיוון שכיוונתי אליו.
לא משוכנע שהמסך הזה הוא המקום להרחיב אותו כדי לטפל גם בטלפונים.
קודם כל מלכתחילה אני לא משוכנע שהוא טוב
וגם:
1. הקוד הקומיט הזה בודק רק את טלפון 1 (יש גם 2,3,4)
2. הוא לא ימצא הבדל עם חסר מקפים וכו... (יש קוד לזה בבדיקת כפילות משפחה לדוגמה)
3. כרגע הוא ימצא טלפון כפול רק אם הוא באותה הכתובת.
נראה לי שצריך כאן טיפול שורש יותר מעמיק

2020-09-29 05:39 UTC, morfi11 commented
צעדים קטנים

On Tue, Sep 29, 2020, 08:38 Noam Honig <notifications@github.com> wrote:

> *@noam-honig* requested changes on this pull request.
>
> זה פחות הכיוון שכיוונתי אליו.
> לא משוכנע שהמסך הזה הוא המקום להרחיב אותו כדי לטפל גם בטלפונים.
> קודם כל מלכתחילה אני לא משוכנע שהוא טוב
> וגם:
>
>    1. הקוד הקומיט הזה בודק רק את טלפון 1 (יש גם 2,3,4)
>    2. הוא לא ימצא הבדל עם חסר מקפים וכו... (יש קוד לזה בבדיקת כפילות
>    משפחה לדוגמה)
>    3. כרגע הוא ימצא טלפון כפול רק אם הוא באותה הכתובת.
>    נראה לי שצריך כאן טיפול שורש יותר מעמיק
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/noam-honig/food-basket-delivery/pull/608#pullrequestreview-498109131>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APQZG6XSVYDHQPV2FH2QOD3SIFXEPANCNFSM4R4OZK3Q>
> .
>

2020-09-29 05:40 UTC, noam-honig commented
בהקשר ללבדוק במהלך הרישום עם טלפון קיים, יש לזה היבט של פרטיות - אני יכול קח לבדוק אם מישהו אחר טרם על ידי הקלדת הטלפון שלו

2020-09-29 07:01 UTC, morfi11 commented
אז נבדוק את השילוב של שם, כתובת וטלפון. מי שיש לו את כל אלה, ממילא חדר
לפרטיות שלי.
לא נציין מה הוא תרם קושם אלא רק שהוא רשום כתורם....
אחרת נצטרך כל הזמן לחפש כפולים ולמרג'ג'  ידנית

המסך הנוכחי לא מדהים אבל גם לא כזה רע. הייתי אולי פותח את הקבוצות בסוג של
היררכיה ומאפשר "אחה את כולם" או משהו כזה במקום להכנס למסך נפרד עבור כל
קבוצה.
אבל להתחלה זה לא רע.

אפשר גם (והתחלתי עם זה אבל ביטלתי בסוף) לעשות לפי טלפון ובהתעלם מכתובת.
כלומר להוסיף צ'קבורס של "בדוק כתובות" כמו זה של הטלפון שהוספתי.


‫בתאריך יום ג׳, 29 בספט׳ 2020 ב-8:40 מאת ‪Noam Honig‬‏ <‪
notifications@github.com‬‏>:‬

> בהקשר ללבדוק במהלך הרישום עם טלפון קיים, יש לזה היבט של פרטיות - אני יכול
> קח לבדוק אם מישהו אחר טרם על ידי הקלדת הטלפון שלו
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/noam-honig/food-basket-delivery/pull/608#issuecomment-700442993>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APQZG6R5U4WBWUGOBVSP5ULSIFXMNANCNFSM4R4OZK3Q>
> .
>

2020-10-11 13:35 UTC, noam-honig commented
Implemented it differently

2020-10-11 13:35 UTC, closed without merging