648 give a gift to a group of volunteers
noam-honig/food-basket-delivery pull request #662
Opened 2021-01-25 10:30 UTC by RoygEy

2021-01-25 13:36 UTC, noam-honig requested changes
Please refer to my comments about try and catch

2021-01-25 13:36 UTC, noam-honig commented on src/app/delivery-history/delivery-history.component.ts
> +                catch (err) {
Why do you need this try catch frase - it's implicit, even if you don't catch it a dialog with an error will appear and display the message.
I prefer to handle such concerns in one place, and not have to write try catch throughout my code.

If you didn't like the way the error is displayed, you are welcome to fix it in:
https://github.com/noam-honig/hug-moms-even-yehuda/blob/aacfdc2c5e4f6c3dab12f139631521968e071cb5/src/app/select-popup/dialog.ts#L208

2021-01-25 13:36 UTC, noam-honig commented on src/app/delivery-history/delivery-history.component.ts
> +            catch (err) {
same comment about the try catch

2021-01-25 15:42 UTC, noam-honig requested changes

2021-01-25 15:42 UTC, noam-honig commented on src/app/delivery-history/delivery-history.component.ts
> +                for await (const h of rows) {
Hi, why "for await? I don't think that the await is needed at this point, since the selectedRows is a simple array.

2021-01-28 08:47 UTC, morfi11 commented
tested locally and it works really well :)
thanks Roy!

2021-01-28 08:48 UTC, morfi11 approved these changes

2021-01-29 13:16 UTC, merged